scrapinghub/shub

shub/login.py, shub/utils.py
Here is a PR to make sure that the netrc file (created by login command) can only be accessed by its owner (0600 permissions).
=> Fix netrc permissions

shub/tool.py
=> Use hifens instead of underscore for command names

shub/deploy_egg.py, tests/samples/deploy_egg_sample_repo.git/setup.py, tests/test_deploy_egg.py
Port of the deploy_eggs_from_url script. I think it fits nicer as a parameter to the existing deploy-egg command.
=> Add --from-url parameter to the 'deploy-egg' command

shub/logout.py, shub/tool.py, tests/test_logout.py
Here is a PR to add a logout command.
=> Add logout command

.gitignore, tox.ini
So, the build will fail for this one, there are some broken tests that weren't running before.
I think we can merge this anyway, since it will reflect the real state of the build.
=> Fix tox config to run tests

shub/tool.py
I think --version is pretty standard (that's what I tried when I've seen the version PR) and click makes it easy :)
=> Add --version to shub

shub/deploy.py, shub/exceptions.py, shub/fetch_eggs.py, shub/utils.py, tests/test_fetch_eggs.py
Better than handling boolean returns. As it has already proved to be prone
to errors (not handling the return values).
Fixes #32
=> Raise ClickException in case of request errors

shub/deploy_reqs.py
Just to give the user some feedback, since the download can take some
time.
=> Display log message at deploy-reqs start

requirements.txt, setup.py, shub/auth.py, shub/deploy.py, shub/fetch_eggs.py, shub/login.py, shub/logout.py, shub/utils.py, tests/test_end_to_end.py, tests/test_login.py, tox.ini
This should be merged after #40.
=> 'shub login' suggesting API key defined in scrapy.cfg

shub/deploy_egg.py, shub/deploy_reqs.py, shub/utils.py, tests/test_deploy_egg.py
This avoids the execution of useless steps.
=> Make subcommands fail early if the user is not logged in

shub/scrapycfg.py
We should be using https:// to access dash and any other api endpoint.
=> Use https by default

tests/test_login.py
I felt the tests intents were lost among the mock machinery.
=> Refactor the login tests

shub/fetch_eggs.py, shub/log.py, shub/login.py, shub/requests.py, shub/tool.py, shub/utils.py
=> Add log and requests commands

tests/test_deploy.py
=> Add test for deploy using the username defined in scrapy.cfg

shub/items.py, shub/log.py, shub/requests.py, tests/test_jobresource.py
=> commands items/log/requests outputting JSON lines

shub/deploy.py, shub/deploy_egg.py, shub/deploy_reqs.py, shub/fetch_eggs.py, shub/items.py, shub/log.py, shub/login.py, shub/logout.py, shub/requests.py, shub/schedule.py, shub/tool.py
Adds extensive help messages for `shub mycommand --help`.
=> Improve per-command documentation

shub/items.py, shub/log.py, shub/requests.py, shub/schedule.py, shub/utils.py, tests/test_jobresource.py, tests/test_utils.py
=> Add 'tail -f' functionality for job resource fetching

shub/utils.py
I missed this when reviewing #96 :/
This is only a hotfix. My suggestion would be to merge this for now, then invest time into a proper refactoring and a new test suite for deploys.
Fixes #106
=> Fix deploy-reqs

README.rst
Once we're happy with this I'll submit a PR to update the [doc page on scrapinghub.com](http://doc.scrapinghub.com/shub.html) (leaving out the advanged config section) and edit [this knowledge base entry](http://support.scrapinghub.com/topic/205471-deploying-your-project-to-scrapy-cloud/) (to the quickstart section?)
=> Extend README

shub/exceptions.py, tests/test_deploy.py
Fixes #99 
This is still up for discussion, but if we do it I'd like to include it in the 1.6 release b/c that's the one where we change parts of the public API anyways.
=> Use more meaningful exit codes

appveyor.yml
Creates the windows binary.
https://ci.appveyor.com/project/scrapinghub-ci/shub
Like travis but for windows.
=> Adding windows shub binary build with appveyor.

.travis-workarounds.sh
Makes tox use the latest installed python version.
Tox using latest (2.7.11): https://travis-ci.org/scrapinghub/shub/jobs/101858533#L151
Fixes: https://travis-ci.org/scrapinghub/shub/jobs/101661794#L228
/cc @jdemaeyer
=> Making osx use latest python for virtualenv creationg.

shub/config.py, shub/utils.py, tests/test_config.py, tests/test_utils.py
Resolves #128
Also contains some maintenance (unification and cleanup)
=> Fix and clean up auto-versioning

shub/utils.py, tests/test_deploy_egg.py, tests/test_utils.py
=> Drop egg name from egg version

shub/config.py, shub/deploy.py
It is safer than using open and then close.
Also removed unused "time" import
=> Use "with" statement to open files

.travis.yml
Fixes #156 (sorry, could've also skipped creating the ticket ;))
=> Fix GitHub releases deploying through Travis

README.rst
Resolves #121 and the last missing checkmark for #115 (resolves #115)
=> Mention binaries and multiple API keys in README

shub/utils.py
=> Improve remote exception printing

.travis.yml, tox.ini
https://codecov.io/github/scrapinghub/shub?pr=173
=> Add coverage report

shub/deploy_reqs.py
Small typo error fix in deploy reqs help text.
=> Fixes an error found in deploy-reqs help text

.gitignore, setup.cfg, tox.ini
The motivation is to avoid bikeshedding on the PRs about PEP-8 stuff. :)
I put a relaxed line limit conforming to the current code, seemed good enough.
Does this look good?
=> Add flake8 to the Travis build

freeze/hooks/hook-hubstorage.py, freeze/hooks/hook-scrapinghub.py, requirements.in, requirements.txt, setup.py, shub/utils.py, tests/test_utils.py
=> Drop hubstorage & fix shub log -f

shub/deploy.py, tests/test_deploy.py
=> Allow glob patterns in egg requirements

docs/deploying.rst
Old link gives no useful information.
=> DOC fixed a link to Scrapy Cloud stack docs

shub/image/deploy.py, shub/image/list.py
=> Replace deprecated get_target with get_target_conf

shub/items.py, shub/log.py, shub/requests.py, shub/schedule.py, shub/utils.py, tests/test_utils.py
=> Update Job URLs to new style

docs/custom-images-contract.rst
Explicitly mention that scripts should be executable and on the search path.
=> Update Custom Images Contract with example

shub/utils.py, tests/test_utils.py
Fixes #255 
~~TODO: Write a test~~
=> Fix subprocess stderr leak in Python2

shub/image/build.py, shub/image/push.py, shub/image/utils.py, tests/image/test_build.py, tests/image/test_push.py, tests/utils.py
This one relies on native `click.progressbar` to provide a bar for `shub image build`, please review.
=> Progress bar for shub image build operation

docs/deploy-custom-image.rst, shub/image/deploy.py, shub/image/upload.py, shub/image/utils.py, shub/utils.py
https://github.com/scrapinghub/shub/pull/260#discussion_r111404777
=> Add deprecation warning for shub image deploy --async parameter

.gitignore, docs/configuration.rst, docs/custom-images-contract.rst, docs/deploy-custom-image.rst, docs/quickstart.rst
please review @vshlapakov @redapple
=> Update Deploying custom Docker images documentation

shub/image/deploy.py, tests/image/conftest.py, tests/image/test_deploy.py, tests/image/test_push.py, tests/image/test_utils.py
=> Improve shub image deploy state reporting

shub/deploy.py, shub/utils.py, tests/test_deploy.py
=> Fix building egg for projects with custom setup.py and invalid scrapy.cfg

shub/image/list.py, tests/image/test_list.py
docker.errors.NotFound is raised when Docker API returns 404, while in case of missing executable Docker API returns 500
=> Fix shub-image-info fallback

docs/custom-images-contract.rst
Provide more details on how crawlers are started.
=> Add a couple clarifications to Custom Images contract.

shub/image/list.py, shub/image/utils.py, tests/image/test_list.py
=> Py3 compatibility fixes for image-list cmd

docs/scheduling.rst, shub/schedule.py, tests/test_schedule.py
=> Schedule: add support for priority, units, tags

shub/image/push.py, shub/image/utils.py, tests/image/test_build.py, tests/image/test_deploy.py, tests/image/test_push.py, tests/image/test_utils.py, tests/image/utils.py
=> Improve image registry parsing logic

.travis.yml, tox.ini
Related comments:
- https://github.com/scrapinghub/shub/pull/324#issuecomment-404869936
- https://github.com/scrapinghub/shub/pull/327#issuecomment-405457942
=> Remove Python 3.3 support

docs/configuration.rst, docs/quickstart.rst
Addresses #335 (extending #337).
=> Describe using environment variables

docs/custom-images-contract.rst
Address https://github.com/scrapinghub/shub/issues/343.
@Gallaecio Could you take a look if it addresses your proposal please?
=> Mention using Scrapy addons in custom image

docs/deploying.rst, setup.py, shub/deploy.py, shub/utils.py, tests/test_deploy.py, tox.ini
I tested with pypi and git packages - the logic as mentioned mirrors code from poetry but I removed the `-e` bits and the hash bits since AFAICT from pipenv those needed to be removed.
=> #347 Add poetry support

shub/config.py, tests/test_config.py
Fixes #264
added default representation of apikey as 'XXXXXXX'
=> [hide-apikey] Fixes #264: Hide apikey

shub/deploy.py, tests/test_deploy.py
https://github.com/scrapinghub/shub/issues/381
=> Deploy: add sources index to requirements.txt file before deploy

setup.py, shub/utils.py
Creating a PR to force the build in appveyor.
=> It tries to fix pip errors on newer version

tests/requirements.in, tests/requirements.txt
Port https://github.com/scrapinghub/shub/pull/398/ to fix coverage-related dependency conflcts.
=> Bump py from 1.8.1 to 1.10.0 in /tests
