setup.py

After ``pip install shub``, shub fails to run due to the missing module
``requests``, as it does not get installed due to not being included in
``install_requires`` of ``setup.py``.
However, ``requests`` does get installed when running ``python setup.py
install``.
Might be nicer for users if ``requests`` gets installed right away.

Adding 'requests' as requirement in setup.py

---

shub/deploy.py

which originally(in scrapy.commands.deploy) received a file and seems to be copypasted without checking

fix "--build-egg" option

---

shub/deploy_reqs.py

When downloading git dependencies with pip, pip would create a `src` directory with the editable sources and put the `pip-delete-this-directory.txt` file.
This messes up the behavior of `utils.build_and_deploy_eggs`, which expects to find only directories for packages inside the `eggs` directory.
This fixes the problem by using [pip's `--src` option][1] to use a temporary dir for the editable sources, this way the eggs dir will be as expected (containing only extracted packages).
[1]: https://pip.pypa.io/en/latest/reference/pip_install.html#install-src

Fix: avoid editable src leftover from pip -e for git dependencies

---

shub/utils.py

In case setup.py doesn't provide a bdist_egg command. Some native
extensions and packages built using distutils don't have it, for
example.
We weren't being able to deploy packages like PyYAML, for example.

Force bdist_egg on utils#build_and_deploy_egg

---

shub/deploy.py

Hey fellows,
The exit status was always `1` when running `shub deploy` -- this fixes it.

fix return code for _upload_egg

---

tests/test_end_to_end.py
tox.ini

Our subcommand tests bypass the click wrappers. I think it's a good idea
to have at least these very simple end to end tests (although not very useful) just to have a little more confidence that no silly bugs have gone unnoticed.
For example, this commit https://github.com/scrapinghub/shub/commit/e73c4e34bceaf8a3469a42a0167306a46e8ef7d7 didn't allow the subcommands to be run, although ```shub```, ```shub --version``` and ```shub version``` were running fine (I tried those when testing the above PR =/).

Add rudimentary end to end tests

---

.travis.yml
shub/deploy_reqs.py
shub/login.py
shub/tool.py
shub/utils.py
tests/test_logout.py

Hey folks,
So, this needs more testing, it just adds some tricks to fix the current tests for Python 3, I'm not sure how much this means for Python 3 compatibility yet.
This basically just adds `.decode()` to the places where are expected bytes in Python 3 (pipe outputs) -- plus some minor refactorings.
The encoding should be `ascii` for all outputs, not sure if I should be explicit about it.
@kmike any advice here? :)

Fix tests for python3 using decode() on pipe output

---

shub/utils.py
tests/test_deploy_egg.py
tests/test_fetch_eggs.py

NoCredentialsException is a ClickException, which is handled nicely by
click, displaying the error msg and returning an exit code != 0.
Fixes #32 and #34

Raising exception on utils#find_api_key

---

shub/auth.py
shub/deploy.py
shub/fetch_eggs.py
shub/login.py
shub/logout.py
shub/utils.py

As discussed on #36, all commands should be in the login/logout workflow.
Fixes #35 
I'll make another PR to facilitate the login reading api keys in scrapy.cfg files.

'shub deploy' using the apikey set by 'shub login'

---

shub/auth.py

Giving higher precedence to the .netrc API key will avoid confusion for
those who have $SHUB_APIKEY set and have also logged in with 'shub login'.
This should be merged after #41

Lower the precedence of $SHUB_APIKEY

---

shub/utils.py

The function `imp.find_module` fails when the given module is installed as a zipped egg, see the session below. Also another reason to drop `imp` in favour is because it was deprecated in python 3.4.
This error makes `shub deploy` unusable when setuptools is installed as egg (i.e. when using conda in OS X).
```
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import setuptools
>>> setuptools.__file__
'/Users/rolando/miniconda/envs/myproject/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/__init__.py'
>>> …
```

Replaced `imp` by `importlib` because `imp` fails to import zipped eggs.

---

shub/login.py
tests/test_login.py

Now we just advise the user to logout first if he wants to change the
credentials.
Fixes #46

Stop returning an error for logged in login attempts

---

shub/deploy_reqs.py
tests/test_deploy_reqs.py

An alternative project id can still be specified via the option -p or
--project flags.
Fixes #52.

Use the project id in the scrapy.cfg as default for deploy-reqs

---

shub/utils.py

If setup.py for a package references `__file__` and there is a c extension (so that it uses the bdist_egg fallback) shub deploy-reqs fails. An example of this is the "regex" package, which gives the error below.
I looked up what pip did and it seems to explicitly set `__file__`, as well as a bunch of other stuff I did not attempt to replicate in this PR: https://github.com/pypa/pip/blob/e41f75b445a32a8d76d0dc7b5f00e8630b48c397/pip/req/req_install.py#L430
```
Building egg in: /tmp/eggsOt6ieD/eggs/regex-2015.07.19
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_egg'
Couldn't build an egg with vanilla setup.py, trying with setuptools...
Traceback (most …
```

Fix bdist fallback when setup.py references __file__

---

shub/deploy_reqs.py
tests/test_deploy_reqs.py

Reverts scrapinghub/shub#54
This breaks the backwards compatibility of the command interface and we want to make a release today.

[MRG+1] Revert "Use the project id in the scrapy.cfg as default for deploy-reqs"

---

shub/utils.py
tests/test_utils.py

This fixes the version names in the same way that
e6f0b1767b093791f457928d2d70bd32764fcf6a fixes the problem with egg
names in #49

[MRG+1] Fix version names when setup.py --version returns many lines

---

shub/deploy.py

For example in projects like https://staging.scrapinghub.com/p/53/deploy/
```
[deploy]
url = https://staging.scrapinghub.com/api/scrapyd/
username = YOUR_LONG_APIKEY_IS_HERE
password =
project = 53
```
Having a way to pass the apikey in the same section than project and endpoint is quite convenient for Dash development, for i.e.:
```
[deploy:vagrant]
url = http://vagrant.host.name/api/scrapyd
username = DEVELOPER_APIKEY
project = 1
```

[MRG+1] passing apikey as username is suggested by dash

---

requirements.txt
setup.py
shub/items.py
shub/schedule.py
shub/tool.py
shub/utils.py
tests/test_items.py
tests/test_schedule.py

The `shub schedule` and `shub items` commands were added. Here is how they work:
Schedule a spider for execution. Example:
```
$ #scheduling 'my_spider' for project 26736
$ shub schedule my_spider -p 26736
$ #scheduling 'my_spyder' for project defined in scrapy.cfg
$ shub schedule my_spider
$ #passing arguments to the spider
$ shub schedule my_spider -p 26736 -a arg1=foo arg2=bar
```
Fetch items from a given job. Example:
```
$ #getting the items scraped by job 26736/2/71
$ shub items 26736/2/71
```

added schedule and items commands

---

RELEASE.md

Documenting release procedure

---

setup.py

because https does not work and value of "url" is displayed in pypi https://pypi.python.org/pypi/shub

replace https with http in homepage url

---

.travis.yml

Idea is to use the container-based infrastructure, to avoid the builds to take so long to start.
See: https://docs.travis-ci.com/user/ci-environment/

Enabling container-based builds on Travis

---

shub/login.py
tests/test_login.py

It wasn't being used and no test caught it

Bugfix: using the suggestion on shub login

---

shub/tool.py
shub/utils.py

This is no longer needed because:
1. shub no longer depends on Scrapy (the big/inconvenient dependency that motivated this mechanism in the first place)
2. shub will be frozen and distributed in a binary form

remove dependecy check per command

---

shub/config.py
tests/test_config.py

Without this, API keys that (by chance) contain only digits will be parsed as integers by PyYAML and run into trouble [here](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub.py#L64)

Make sure API keys are always returned as string

---

shub/schedule.py
tests/test_schedule.py

Fixes #84.
I chose `--set` as long option name because it matches `scrapy`. It's not really consistent with `--argument` though...

Allow passing settings via schedule

---

shub/utils.py
tests/test_utils.py

Adds support for
* `shub items 1/1` (fetches from default project)
* `shub items otherproject/1/1` (fetches from `otherproject` defined in `scrapinghub.yml`)

Allow scrapinghub.yml targets in items/log/requests

---

README.rst

This introduces 'Quickstart' and 'Advanced Configuration' to the readme file. This could possibly be embedded from http://doc.scrapinghub.com/shub.html, with the per-command documentation being left to ``shub xyz --help``.

Bring back documentation

---

shub/schedule.py
tests/test_schedule.py

Allow equal sign in spider args and job settings

---

shub/deploy.py
shub/utils.py
tests/test_deploy.py
tests/test_utils.py

In some cases deploy can stream responses, and in most such cases you don't want to get full deploy logs each time. A better way could be checking last line and if it has an error status, then show last N rows from the log (N=30).
Review, please.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/scrapinghub/shub/96)

Better deploy results handling for stream responses

---

shub/config.py
shub/utils.py
tests/test_config.py
tests/test_login.py
tests/test_logout.py

Auto-migration for `.netrc` and `.scrapy.cfg` into `.scrapinghub.yml` and for `scrapy.cfg` into `scrapinghub.yml`.
I think this is a solution that minimises the pain we induce users during migration

Migrations for new configuration

---

tests/test_utils.py

Should fix [this issue](https://travis-ci.org/scrapinghub/shub/jobs/100832815#L246) with the `job_resource_iter` test that appears in OSX environments

Fix job_resource_iter test that only fails on OSX

---

.travis-workarounds.sh
.travis.yml

This PR adds OS X in the Travis build to run the build.
Since Travis doesn't support python in OS X I've added python installation with brew in `travis-workarounds.sh` (only when $TRAVIS_OS_NAME is `osx`)
The final build matrix is:
- TOXENV=py27,freeze in linux (Creates linux binary)
- TOXENV=py27,freeze in osx (Creates osx binary)
Link to working build: https://travis-ci.org/scrapinghub/shub/builds/100935289
@dangra @pablohoffman should also add TOXENV=py27 for osx?

Adding OS X shub builder

---

shub/config.py
shub/deploy.py
shub/fetch_eggs.py
shub/login.py
shub/schedule.py
shub/utils.py
tests/test_config.py
tests/test_schedule.py
tests/utils.py

This is purely cosmetic, but `shub` can do more than deploy projects now, and the configured API endpoint should reflect that.
README should be updated when/if this is merged, it's not in here yet b/c it would conflict with #105

Stop using scrapyd as API endpoint

---

shub/config.py
tests/test_config.py

Fixes #112 
Without this, if the `scrapy.cfg` default deploy URL differed from our default URL, each different target from `scrapy.cfg` would get its own endpoint. This was only an implementation detail when we were only reading from `scrapy.cfg`, but produces unnecessarily verbose output now that we're auto-migrating to `scrapinghub.yml`. E.g. if we start from this `scrapy.cfg`:
```
[deploy]
url = deploy_url
project = 111
[deploy:prod]
project = 222
```
Without this PR we receive this output:
```
endpoints:
default: deploy_url
prod: deploy_url
projects:
default: 111
prod: prod/222
```
Output with this PR:
```
endpoints:
default: deploy_url
projects:
default: 111
prod: 222
```
This also fixes a bug where the non-default targets from `scrapy.cfg` were not associated with an API key in case …

Properly migrate multiple deploy targets from scrapy.cfg

---

appveyor.yml

Some unit tests fail on windows when try to open `~/.scrapinghub.yml`.
The problem is that `os.path.expanduser` uses `HOME`, `USERPROFILE`, `HOMEPATH` and `HOMEDRIVE` to replace `~`. When tox runs it doesn't pass these variables to the execution and so the expansion doesn't happen.
This only affects windows builds (appveyor.yml)

Pass windows home env vars to tox to allow os.path.expandvars to work.

---

README.rst
shub/config.py
shub/deploy.py
shub/login.py
shub/logout.py
tests/test_config.py
tests/test_deploy.py
tests/test_logout.py

Add a wizard when users run `shub deploy` but have no `scrapinghub.yml` (and no deploy configuration in `scrapy.cfg`). Users will be prompted for a project ID, access rights to this project will be checked, and users can save it as default to `scrapinghub.yml` if wished.
Also contains some additional maintenance:
* PEP8ify `shub/deploy.py`
* Clean up `shub.deploy.cli()` (outsource `list_targets`)
* Rename `shub.config.update_config()` to `update_yaml_dict()`, since `update_config()` does not work on `ShubConfig` objects
* Update migration banner to reflect next shub version
Resolves #126.

Deploy onboarding + maintenance

---

shub/deploy.py
shub/deploy_egg.py
shub/deploy_reqs.py
shub/utils.py
tests/test_utils.py

Stand-alone deploy did not work previously as `sys.executable` does not point to the python interpreter when frozen.
Also introduces error messages when `python` or `pip` are not available on the system but are required by a command.

Fix standalone deploy and improve behaviour for missing dependencies

---

shub/fetch_eggs.py
shub/login.py

When constructing an URL with key/value data, the requests library allows passing
them as a dictionary in the "params" argument.
I think that line is easier to read after this change.
See http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls

use params argument of the requests library

---

freeze/hooks/runtime-hooks.py
requirements.txt
setup.py
shub/deploy.py
shub/deploy_egg.py
shub/deploy_reqs.py
shub/utils.py
tests/test_deploy_reqs.py
tests/test_utils.py
tox.ini

:boom: **DO NOT MERGE** :boom:
Resolves #129 
Makes `shub` Batteries Included™ by:
- Untarring/unzipping with the Python library instead of calling `unzip` or `tar` (which are seldomly available on Windows)
- Using `pip` as Python module instead of calling it as subprocess
Now if only I knew how to call a separate Python interpreter using PyInstaller...
This is WIP. ~~It works fine when I install `shub` via `pip` but makes problems in the stand-alone versions. In particular, `pip` fails to download any packages when I run it under Windows, for no apparent reason (but has no problems doing it when I run it under Linux using `wine`...).~~
Update: First running `pip.exe install -d tmp requests` (i.e. downloading `requests` with the system-wide `pip` install), then running `shub deploy-egg …

[WIP] Drop dependency to external commands

---

.travis.yml
appveyor.yml

On tagged commits (i.e. releases), compress the binary into an archive (one per OS) and upload it into the GitHub release corresponding to the tag.

Auto-upload binaries to GitHub release on tagged commit

---

shub/utils.py

When running `shub log 1` I got this traceback:
```python
Traceback (most recent call last):
File "/home/carlosp420/.virtualenvs/shub/bin/shub", line 9, in <module>
load_entry_point('shub==1.5.0', 'console_scripts', 'shub')()
File
"/home/carlosp420/.virtualenvs/shub/local/lib/python2.7/site-packages/click/core.py",
line 716, in __call__
return self.main(*args, **kwargs)
File
"/home/carlosp420/.virtualenvs/shub/local/lib/python2.7/site-packages/click/core.py",
line 706, in main
e.show()
File
"/home/carlosp420/.virtualenvs/shub/local/lib/python2.7/site-packages/click/exceptions.py",
line 48, in show
echo('Error: %s' % self.format_message(), file=file, color=color)
File
"/home/carlosp420/.virtualenvs/shub/local/lib/python2.7/site-packages/click/exceptions.py",
line 79, in format_message …
```

AttributeError when trying: "shub log 1"

---

shub/deploy_egg.py
shub/deploy_reqs.py
shub/utils.py
tests/test_utils.py

Unify downloading PyPI packages and improve support for different pip versions. This should work all the way back to pip 1.0 now (which is the version in Ubuntu Precise). Probably earlier, but that's as far as I tested.
`pip install -d` was deprecated in 8.0.0 in favour of `pip download`. The `-d` flag has stayed to configure the download destination.
`--no-use-wheel` was introduced in pip 1.4.0 (and was default before that), deprecated in pip 7.0.0 in favour of `--no-binary=:all:`, and completely removed in 8.0.0.

Improve pip support

---

freeze/tests/run.py

This test fails randomly because of timeout on AppVeyor. E.g. [here](https://ci.appveyor.com/project/scrapinghub/shub/build/master-84) but not in [this run with identical code](https://ci.appveyor.com/project/scrapinghub/shub/build/master-83)

Extend poll timeout in freeze test

---

shub/items.py
shub/log.py
shub/requests.py
shub/utils.py
tests/test_utils.py

With this PR, you can do:
shub log -f <PASTE DASH JOB LINK HERE>
Beats typing or editing the link to supply only the job key every time. ;)

Add support for job URLs as job spec

---

shub/config.py
shub/deploy.py
shub/utils.py
tests/test_config.py
tests/test_deploy.py

Fixes #149 
Also, `shub deploy` will now also call the deploy wizard when there is a `scrapinghub.yml` without default target.

Don't migrate non-integer project names

---

.travis.yml
appveyor.yml
freeze/tests/run.py
tox.ini

Currently, there is [an error while Travis tries to deploy shub to PyPI](https://travis-ci.org/scrapinghub/shub/jobs/108800444#L457). The reason is that `python setup.py sdist` and `PyInstaller` both use the `dist` folder, and whatever script deploys to PyPI doesn't like the `shub` executable in `dist`.
That's why there's no source tarball on PyPI for our newer releases.

Fix PyPI releasing

---

shub/utils.py
tests/test_utils.py

shub should not tell `Run your spiders at ..` after all the deploy errors when using streaming responses. There's a check already for successful deploys, it's easy to use its result and raise a correct error.
Please, review, and let me know if it can be done in a better way. // cc @dangra

Correct status of streaming deploy error

---

shub/config.py
shub/deploy.py
shub/deploy_egg.py
shub/deploy_reqs.py
shub/fetch_eggs.py
shub/schedule.py
shub/utils.py
tests/test_config.py

Add support for specifying stack and requirements file per-project using the following syntax:
```
stacks:
ocr: ocr:v1.2
projects:
default: 
id: 123
stack: scrapy:v1.1
prod: 1  # Will use Dash's default stack
ads:
id: 2
stack: ocr
```
Also makes sure `shub deploy` will always deploy the same configuration as `shub deploy 123`.
Resolves #171. Closes #172.

Add support for stack and reqfile configuration

---

.travis.yml
appveyor.yml
freeze/tests/fakeserver.py
freeze/tests/run.py
setup.cfg
shub/utils.py
tests/test_utils.py
tox.ini

* Add a missing py3 port in `shub` (specifically looking for Python 2.7)
* Port `freeze/tests` to py3
* Freeze and deploy binaries with Python 3.5 only
* Build universal wheels (`py2.py3` tag) to upload to PyPI

[WIP] Fix binary freezing

---

shub/log.py
tests/test_jobresource.py

I noticed shub log -f was failing with unhandled exception when it encountered log message with non-ascii characters. This commit fixes that.

shub log should not fail on non-ascii

---

shub/config.py
shub/utils.py

This PR adds warnings in two cases:
1. When an API endpoint uses `staging.scrapinghub.com`. See also https://scrapinghub.atlassian.net/browse/SC-725
2. When an API endpoint uses HTTP. See also https://scrapinghub.slack.com/archives/security/p1469507392000003
Personally I even wanted to directly "correct" those inappropriate endpoints, since we might assume that users of `shub` are all accessing only Scrapinghub's API (..can we?). But I'm afraid that might look too aggressive.

Added: Warnings when an API endpoint is using staging.scrapinghub.com or HTTP

---

README.rst
shub/config.py
shub/deploy_egg.py
shub/deploy_reqs.py
tests/test_config.py

/cc @dangra are you ok with deprecating `deploy-egg` and `deploy-reqs` like this and removing them from the docs?

Allow specifying requirements file under requirements dict parameter

---

shub/items.py
shub/log.py
shub/requests.py
shub/utils.py
tests/test_utils.py

Adds the `-n/--tail` option to `shub log`, `shub items`, and `shub requests`. E.g., `shub log 1/1 -n 5` retrieves the five latest log entries.
Closes #195 
Kind of closes #122

Add --tail functionality to log/items/requests

---

shub/copy_eggs.py

Fixes #183.
Also contains some additional maintenance of `copy-eggs`:
* Use `get_target_conf` instead of the deprecated `get_target`
* Limit line length to 79, remove unnecessary blank lines

Don't copy Dash Addon eggs

---

freeze/shubrunner.py
shub/__main__.py
tox.ini

`python -m shub` is useful during development (when I explicitly don't want to run `/usr/bin/shub`) and when `/usr/bin/shub` (or the Windows equivalent) was for some reason not created (from what I gather this might happen on Mac machines sometimes).

Add __main__.py to allow invoking shub with python -m shub

---

requirements.in
requirements.txt
setup.py
shub/config.py
tests/test_config.py
tests/test_login.py
tests/test_migrate_eggs.py

`ruamel.yaml` was giving trouble for Windows users sometimes. It's also a bit of an obscure dependency, so I think we should revert to upstream.
The implication of this is that key ordering and comments will no longer be preserved when we update YAML files. As it's rare that a config file is edited manually and then written automatically to afterwards, this shouldn't be much of a deal.

Drop ruamel.yaml in favour of PyYAML

---

shub/deploy.py

Users are reporting import errors for `setuptools.msvc` on systems with old setuptools versions.

setuptools.msvc is needed only for >v24.0.0

---

shub/utils.py
tests/test_utils.py

Dash logic has pattern matching to check correctness of version string on deploy, and in some cases will deploy reject requests from shub tool due to spaces or some other forbidden chars (for example SVN allows using spaces in a branch name). Let's polish clients experience and clean version string before doing any external requests.
Review, please.

Clean version string with pattern

---

shub/image/test.py
tests/image/test_test.py

Drop redundant check for sh-ep-scrapy.
Initial intention before https://github.com/scrapinghub/shub/pull/229#issuecomment-276886774 was to check for `scrapinghub-entrypoint-scrapy` only if there's Scrapy installed, but it doesn't play nice with non-python code.
I also noticed that we don't clean temporary containers after tests, let's improve it as well.

image test: drop check for sh-ep-scrapy

---

shub/tool.py

It's a very popular option for getting a help message, can't help but use it, it's already a muscle memory I guess. So annoying that click doesn't have it by default.

Add -h option to get help message

---

.travis-workarounds.sh
.travis.yml
appveyor.yml
shub/image/utils.py
tox.ini

Plus a small fix for `shub image check`: Previously, when updating the temporary file with status urls in `shub image check` once the line limit for that file had been reached, an _arbitrary_ line was removed via `dict.popitem()`. Because of an implementation detail in CPython, this used to fall in line with what we wanted, deleting the oldest entry. The fix makes sure we always explicitly delete the oldest entry. (The `dict` implementation has changed in CPython 3.6 and would now delete the newest dictionary entry instead.)

Enable tests for Python 3.6

---

shub/image/build.py
shub/image/deploy.py
shub/image/init.py
shub/image/utils.py

Some messages and docstrings still refer to the legacy `shub-image` tool, such as this message I got when deploying an image:
You can check deploy results later with 'shub-image check --id 0'.
This PR fixes those.

Rename 'shub-image' to 'shub image' in messages and docstrings

---

shub/image/build.py
shub/image/push.py
shub/image/upload.py
tests/image/conftest.py
tests/image/test_build.py
tests/image/test_push.py
tests/image/test_upload.py

- Test image before `shub image push`.
- Skip tests if necessary with `-S/--skip-tests`.
- In `shub image upload` command tests are running during the build.
- Update tests for build, push and upload commands.
- Migrate test cases for build and push commands from unittest.TestCase to idiomatic pytest test cases with fixtures.
- Added new tests for -S/--skip-tests flag.
- Added project_dir fixture and removed boilerplate code from build and push commands tests.

Test image before `shub image push`

---

shub/deploy.py
shub/deploy_egg.py
shub/exceptions.py
shub/utils.py
tests/test_deploy_egg.py
tests/test_utils.py

We had a couple of different implementations and helpers for calling subprocesses floating around, this PR unifies them.
It also removes the "Retry on EINTR" functionality as that has been [included in CPython](https://www.python.org/dev/peps/pep-0475/).

Unify calling subcommands

---

shub/image/build.py
shub/image/push.py
tests/image/conftest.py
tests/image/test_build.py
tests/image/test_push.py

Updated test fixtures because imported command should be mocked in each individual module.
Also sorted imports in the shub.image.build and shub.image.pull modules.

Update shub image test command imports

---

requirements.in
setup.py
shub/image/push.py
shub/image/utils.py

The goal of the changes is to improve verbosity of push progress, cause events stream in verbose mode is too verbose and hard to read, and non-verbose mode is silent and can wait for a lot of time w/o any sign of life, especially when there're a lot of layers to push and network is flaky.
Initial attempt was to achieve similar results with built-in [click.progressbar](http://click.pocoo.org/5/api/#click.progressbar), but there're a few issues with it:
- it doesn't support multiple bars and it's tricky to work it around
- single bar works fine, but we don't have any variable to track total progress with enough details - only as amount of layers left to push (but if some layers are large it doesn't work good)
- almost always several layers are being pushed at the same time, and it's hard to …

Shub image push progress with tqdm

---

shub/image/init.py
shub/utils.py
tests/image/test_init.py

It failed with TypeError if there was not scrapy.cfg in the current directory.
Update help message and error message.
Update base image in Dockerfile template.
Update list of recommended Python packages.
Use click.confirm to prompt for save file confirmation.
Deprecate --base-deps parameter.
Update init command tests.

Fix shub image init

---

shub/config.py
tests/test_config.py

Fixes a bug in #244 by removing existing "plural" dictionaries containing only a `default` when we write the singleton configuration.
Before this, if we had an existing `scrapinghub.yml`:
```
projects:
default: 12345
```
and then loaded and saved from this file:
```python
In [1]: from shub.config import ShubConfig
In [2]: conf = ShubConfig()
In [3]: conf.load_file('scrapinghub.yml')
In [4]: conf.save('scrapinghub.yml')
```
the new `scrapinghub.yml` would contain both the singleton and the plural directives:
```
project: 12345
projects:
default: 12345
```
so that it was invalid:
```python
In [5]: ShubConfig().load_file('scrapinghub.yml')
BadConfigException: You cannot specify both 'project' and a 'default' key for 'projects' in the same file
```

Fix saving configuration shortcuts after update

---

shub/deploy.py
shub/image/build.py
shub/image/init.py
shub/image/utils.py
shub/utils.py
tests/image/conftest.py
tests/image/test_build.py
tests/image/test_init.py

It makes more sense to create `setup.py` if it doesn't exist on `init` step instead of `build`.
Review, please.

Create setup.py on shub image init

---

shub/image/push.py
tests/image/test_push.py
tests/utils.py

For events without total progress take current as total.
For events with current progress greater than total - update total for the bar.
Fixes this:

Push progress bars - improve handling of push events

---

requirements.txt
shub/config.py
shub/deploy.py
shub/exceptions.py
shub/image/build.py
shub/image/deploy.py
shub/image/list.py
shub/image/push.py
shub/image/test.py
shub/image/upload.py
tests/image/test_list.py
tests/image/utils.py
tests/test_config.py
tests/test_deploy.py
tests/test_migrate_eggs.py
tests/utils.py

The goal of the PR is to improve logic of `shub deploy` to provide the following things:

Shub deploy improvements

---

freeze/tests/run.py
shub/config.py
shub/deploy.py
shub/image/build.py
shub/image/init.py
shub/login.py
shub/logout.py
shub/utils.py
tests/image/test_build.py
tests/test_config.py
tests/test_deploy.py
tests/test_end_to_end.py
tests/test_login.py
tests/test_logout.py
tests/test_utils.py

* Move `update_yaml_dict` from `shub.config` into `shub.utils`
* Move onboarding wizard from `shub.deploy` into `shub.utils`
* In `shub image init`, don't look for `scrapinghub.yml`, but for `scrapy.cfg`
* Extend the onboarding wizard so that it also asks for a Docker registry (if called from a `shub image` command)
* In `shub image build`, call the onboarding wizard if we can't find a `scrapinghub.yml`, or can't find a Docker registry in it

Add "Create scrapinghub.yml" wizard to shub image build

---

shub/deploy.py
shub/image/build.py
shub/utils.py
tests/image/test_build.py
tests/test_deploy.py
tests/test_utils.py

When there's no `scrapinghub.yml`, `shub deploy 108106` will now no longer try to deploy to 108106 as Scrapy project (or fail with "No Scrapy project found"), but:
* if there is a `scrapy.cfg` and no `Dockerfile`, save 108106 as default target and deploy as Scrapy project
* if there is a `Dockerfile` and no `scrapy.cfg`, save 108106 as default target, ask for image repository, and deploy as custom image
* ask whether to use custom image if there are both `Dockerfile` and `scrapy.cfg`
The wizard will never touch any configuration if there already is a `default` target defined in `scrapinghub.yml`.
`shub image upload 108106` behaves similarly, but will always deploy as custom image project.
Closes #263

Refactor onboarding wizard

---

shub/config.py
tests/test_config.py

Fail with an "ambiguous configuration" error message and a link for these three ambiguous configurations:
1. Both global non-false `image` and global `stack` configured
2. Global `image` configured and target project has `stack` option but not `image: false`
3. Target project has both `stack` option and non-false `image` option
Also replaces a couple of `BadParameterException`s that were raised on bad configurations with `BadConfigException`s (/cc @vshlapakov)

Fail on ambiguous image configuration

---

tests/image/test_build.py
tests/image/test_push.py
tests/utils.py

Our tests for the progress bar output during custom image building/pushing sometimes randomly fail. This is because the output of carriage returns, newlines, and ANSI escape sequences is dependent on the machine that runs the test.
For example, [this test](https://ci.appveyor.com/project/scrapinghub/shub/build/master-554/job/5e7mabanrd3cppe4#L138) failed because the actual output was `\x1b[A\\n\\x1b[AThe image registry/user/project:test pushed successfully.` while the expected output was `\\n\\nThe image registry/user/project:test pushed successfully.`
This PR should make the tests consistent by stripping these characters before checking the expected output.

Make progress bar output tests independent of formatting details

---

docs/custom-images-contract.rst

Please review and let me know if it can be improve in some way. There're some fields I haven't include in the list because think they are internal, also probably we should provide more real-life examples (at least for custom ``meta`` items if we're going to support it in the future).

Describe SHUB_JOB_DATA env variable

---

shub/image/deploy.py
shub/image/list.py
shub/image/test.py
shub/image/utils.py
tests/image/test_deploy.py
tests/image/test_list.py

We're introducing a new command to Kumo contract: it's called `shub-image-info` and will deprecate current `list-spiders`. Comparing with `list-spiders` command - the new command should return JSON encoded metadata for a given image, incl. a project type, spiders metadata and probably some other fields in the future. As now we're changing the way how arguments and settings are being passed to a spider/script, scripts become a Scrapy-specific feature, and should be included into the same spiders list with `py:` prefix.
Important note, that we must provide backward compatibility, so if `shub-image-info` is not found, there's fall back to `list-spiders` with a deprecation warning.
Please, review.

Replace list-spiders with shub-image-info

---

shub/image/deploy.py
shub/image/list.py
tests/image/test_deploy.py
tests/image/test_list.py

shub tool should extract `project_type` info from `shub-image-info` and pass it on deploy.
Review, please.

Extract and pass project_type on deploy

---

docs/custom-images-contract.rst

Describe extending custom images contract with a new ``shub-images-info`` command.
The PR is complete, awaiting for next shub release and update examples in custom-images-examples repo.

Extend contract with shub-image-info

---

docs/custom-images-contract.rst

We assume that when parse command output but docs suggest multiline output

shub-image-info output should be a single line

---

shub/image/deploy.py

According to the last changes in [SH contract](https://shub.readthedocs.io/en/stable/custom-images-contract.html), there's `shub-image-info` command responsible for getting metadata and spiders list from a custom image. And we still support scripts in SH, so there's a need to get it in a similar way. However we can't implement getting scripts in default `shub-image-info` implementation in `scrapinghub-entrypoint-scrapy` (because it knows nothing about main project python egg and its internals), but we still should provide some workaround to make it work with custom images.
My proposal here is to always try to extract scripts if they're not found in `shub-image-info` output. Additional time is small, but this trick will help to solve the problem and bring scripts to custom images with …

Extract scripts if not found in shub-image-info

---

.travis.yml

Temporary measure, we have to drop Python 3.3 support in the next shub version.

Pin virtualenv to pass tests for Py3.3

---

setup.py
shub/__init__.py
shub/config.py
shub/deploy_egg.py
shub/deploy_reqs.py
tests/samples/deploy_egg_sample_project/setup.py

Some docs pointing to `docs.sh.com` are outdated, let's update it.

Replace doc.sh.com links with actual ones

---

shub/deploy.py
shub/exceptions.py
shub/utils.py
tests/test_deploy.py

We have 50MB limit for incoming requests, let's check project egg(s) total size before deploying to avoid errors like `Deploy failed: ('Connection aborted.', OSError("(32, 'EPIPE')",))` and fail gracefully with a readable error message.

Check request files total size on deploy

---

docs/deploying.rst
shub/deploy.py
tests/requirements.in
tests/requirements.txt
tests/test_deploy.py

As we talked on https://github.com/scrapinghub/shub/issues/312 this is a PR to add support to Pipfile on shub deploy.
This PR doesn't touch anything related to `shub image...` and simply uses pipenv internals to parse `Pipfile.lock` into a `requirements.txt` file.
I have opted to keep using `requirements_file` settings where if the user gives it the value of `Pipfile` or `Pipfile.lock` it tries to parse `Pipfile.lock`
If these changes are ok, I believe there will also be docs changes needed, please instruct me if that is the case.

Add Pipfile support to shub deploy

---

docs/deploy-custom-image.rst
shub/image/build.py
shub/image/upload.py
tests/image/test_build.py
tests/image/test_upload.py

This modification allows to pass a custom Dockerfile name instead of assuming the default value ('Dockerfile') when building images. This is useful when you want to manage different Dockerfiles in the same repo.

Allow custom Dockerfile names

---

shub/deploy.py
tests/test_deploy.py

Fixes https://github.com/scrapinghub/shub/issues/317
VCS packages don't generate hashes, and `convert_deps_to_pip` generates requirements with hashes.
When we run `pip install -r requirements.txt` with a `requirements.txt` like:
```
package==1.0 --hash=hash
git+https://github... # note that it doesn't have the --hash
```
It fails since the vcs package can't be hashed
Thus we must delete these hashes from the object before giving it to `convert_deps_to_pip`
Btw, they do something similar in their own code: https://github.com/pypa/pipenv/blob/master/pipenv/utils.py#L793

Ignore hashes on Pipfile.lock to play nice with vcs packages

---

.travis.yml

When updating test environments for Travis in https://github.com/scrapinghub/shub/pull/311, I replaced a freeze env with regular one to run common tests on OSX with different Python, and it wasn't ideal solution because we still need the freeze env to build a binary for OSX - this PR recovers it.

Recover an env to build OSX binary

---

shub/image/deploy.py
shub/image/upload.py

`async` is a reserved word in Python 3.7 (https://docs.python.org/3.7/reference/lexical_analysis.html#keywords) and `shub` uses it as a variable.
This PR closes #325 and remove the use of this reserved word, avoiding SyntaxError when running in Python 3.7.

Remove use of Py3.7 reserved word

---

shub/image/utils.py
tests/image/test_utils.py

Fix #331, use DOCKER_API_VERSION instead of DOCKER_VERSION

Fix #331, use DOCKER_API_VERSION instead of DOCKER_VERSION

---

docs/deploying.rst

Previously it was acting as a block quote.

Enclose example in code block

---

requirements.in
requirements.txt
setup.py
shub/schedule.py
shub/utils.py
tests/test_schedule.py
tests/test_utils.py

Instead of the legacy `scrapinghub.Connection` class.
This time I did try scheduling spiders with default unit amounts set in Dash and it works :sweat_smile: (#329)

Use scrapinghub.ScrapinghubClient

---

shub/image/__init__.py
shub/image/run/__init__.py
shub/image/run/wrapper.py
shub/image/utils.py
tests/image/test_run.py

We want to have a separate command to be able to run a custom image locally, for test/debugging purposes. The idea is to mimic (though simplify) SC approach by using a separate wrapper to read crawl process results from FIFO and print it to container stdout. The wrapper is written in Python for simplicity, but could be rewritten with anything more basic (like Bash) in the future.

Add a command to run custom image locally

---

shub/image/build.py
shub/image/upload.py
tests/image/test_build.py
tests/image/test_upload.py

enabled to use no-cache option when executing "shub image build" command.
```
$ shub image build --no-cache
```
All I implemented is to pass the no-cache option to the docker client.

Add "no-cache" option on "shub image build" command

---

requirements.txt
shub/cancel.py
shub/tool.py
shub/utils.py
tests/test_cancel.py

This PR adds a new command called `cancel`, which aims to stop running and awaiting jobs. 
It uses the new `python-scrapinghub`'s `cancel` method.
Usage examples:
$ shub cancel <project_id> <spider_id>/<job_id> <spider_id>/<job_id> ...
$ shub cancel <spider_id>/<job_id> <spider_id>/<job_id> ...
$ shub cancel --force <spider_id>/<job_id> <spider_id>/<job_id> ...

KUMO-3333: Adding a new command to cancel multiple jobs

---

shub/image/build.py

The logic should drop extra new lines only, not any last character.

Use rstrip to drop extra newline (closes #361)

---

shub/image/utils.py
tests/image/test_utils.py

If we are doing are getting the insecure credentials and we have username or password, an alert will raise.

Insecure exception with credential should raise warning

---

shub/image/push.py
shub/image/upload.py
tests/image/test_push.py
tests/image/test_upload.py

After docker-login step is completed once, it adds a record to its local config with all key data about login, and doesn't try to re-authenticate unless the data is gone. However, we noticed a few cases when explicit re-authentication is required. The PR adds an option to enforce the re-authentication process if needed.

Image push: provide explicit option to re-auth

---

shub/image/build.py
tests/image/test_build.py

This change makes `shub image build` behave like `docker build --rm=true .` which has become the default in docker command but was preserved in the client for backward compatibility. I don't know if anyone relies on this behavior so maybe it doesn't make sense but if it does I suppose it's better to shelve this till next major release.

Cleanup intermediate build containers 

---

shub/image/utils.py

In order to handle cases when 2 versions of docker bindings installed at the same time, we'll need to check it; otherwise instantiating a docker client instance would fail with confusing `TypeError`.

Ensure docker doesn't clash with docker-py

---

shub/image/build.py
shub/image/upload.py
tests/image/test_build.py
tests/image/test_upload.py

Needed for passing things like private credentials without hard coding them in Dockerfile.

allow to pass build arguments to docker client

---

.travis.yml
appveyor.yml
tox.ini

Python 3.5 reached its EOL in September 2020, we had to drop the support for it a long time ago.

Stop using Python 3.5 for CI

---

shub/deploy.py

Workaround for #417. Not a complete fix, we should look into replacing these functions, maybe with the `requirements` or `lock` commands.

Import pipenv utils from new location

---

shub/deploy.py
tests/test_deploy.py

Since Pipenv v2022.8.30 the function `convert_deps_to_pip` returns a list of strings containing all the dependencies found in the Pipfile converted to Pip format. So, I added a try/exception statement to catch the `TypeError` exception, when the previous code tries to open the temporary file, and write the dependencies to the requirements file.

Fix deps conversion

---

.github/workflows/tests.yml
shub/utils.py

Quick fix (no tests :smiling_face_with_tear:) after internal report from developers.
With the following patch (after line https://github.com/scrapinghub/shub/blob/v2.14.3/shub/utils.py#L132)
```diff
diff --git a/shub/utils.py b/shub/utils.py
index 11665ec..c32ba67 100644
--- a/shub/utils.py
+++ b/shub/utils.py
@@ -130,6 +130,8 @@ def make_deploy_request(url, data, files, auth, verbose, keep_log):
def _check_deploy_files_size(files):
"""Ensure that request's files total size is less than current limit."""
ctx = click.get_current_context(silent=True)
+    import pdb
+    pdb.set_trace()
if not isinstance(files, list) or ctx and ctx.params.get('ignore-size'):
return
files_size = sum(
```
we can see the option name:
```
$ shub deploy --ignore-size
Packing version 40136e4-main
Deploying to …
```

Fix option name (ignore-size -> ignore_size)

---

shub/deploy.py

This PR fixes the check errors in https://github.com/scrapinghub/shub/pull/432 .

Fix E231 and E501 flake8 errors in CI

---

docs/deploying.rst
docs/scheduling.rst
shub/config.py
shub/deploy.py
shub/items.py
shub/log.py
shub/login.py
shub/requests.py
shub/utils.py
tests/image/test_deploy.py
tests/image/test_list.py
tests/test_config.py
tests/test_deploy_reqs.py
tests/test_utils.py

Resolves https://github.com/scrapinghub/shub/pull/432.

use app.zyte.com now

---

tests/test_deploy.py

Taken from #434:
> Failing on master for pipenv>2023.2.4, which was the last version supported for python<3.8
Splitting so we can release #432 sooner.

fix tests for latest pipenv

---

shub/schedule.py

schedule command: Scrapinghub -> Zyte

---

.github/workflows/tests.yml
setup.py
shub/deploy_egg.py
shub/image/run/wrapper.py
shub/image/utils.py
shub/utils.py
tests/test_config.py
tests/test_schedule.py
tests/test_utils.py

Adds support for Python 3.12. Main changes:
- `NamedTemporaryFile` no longer has a `delete` attribute, presumably this wasn't part of the public API: https://github.com/python/cpython/commit/743453a5541d3a6f19046459d22a7991ecb88223#diff-6553a99f3ae04c9fc9c2349ac27037bfe3b274d5ca54d5800d9c5b5f11e29d21L470 (refactored to not rely on it)
- Deprecated assertion helpers were [removed](https://docs.python.org/3/whatsnew/3.12.html#id3) (simple renames)
- `distutils` was [removed](https://docs.python.org/3/whatsnew/3.12.html#distutils) (replaced version classes with equivalent one from `packaging`)
- `pkg_resources` is [no longer provided by default](https://docs.python.org/3/whatsnew/3.12.html#ensurepip) (was also deprecated, so replaced it with `importlib.metadata`)
- Deprecated …

add support for python 3.12

---

shub/image/utils.py
tests/image/test_utils.py

Fixes https://github.com/scrapinghub/shub/issues/444

Stop hardcoding the default Docker version

---

docs/deploy-custom-image.rst

- upload command does not support `--target` parameter and returns error.
- As per code target can be specified as an argument.
- Updated example and  and options

[Documentation] `shub Image upload` documentation correction.

---

.github/workflows/checks.yml
.github/workflows/freeze-release-publish.yml
.github/workflows/tests.yml
tests/test_deploy.py
tox.ini

Since pipenv version 2024.3.0, an additional whitespace character is placed between the package name and the @ character (see https://github.com/pypa/pipenv/pull/6282).

Fix VCS pip line entry in test suite

---

.github/workflows/tests.yml
docs/deploying.rst
setup.py
shub/deploy.py
tests/requirements.txt
tests/test_deploy.py
tox.ini

The previous lockfile parser did not work reliably for Poetry 1.2 and later due to the new lockfile format (e.g., it did not take markers into consideration). This solution should work for all Poetry versions since it uses the `poetry export` command to generate a `requirements.txt` file.
I encountered an issue where shub deploy failed with a requirement error because it attempted to install `pywin32`. This happened because the marker `sys_platform == "win32"` was missing from the generated requirements.txt file.
I’m not sure if it still makes sense to test the conversion from poetry.lock to requirements.txt, as Poetry's test suite already covers this extensively. I adapted the test, but in my opinion, it could be dropped.
The biggest caveat of the new implementation is that users need to …

Add support for current Poetry versions

---

shub/login.py

Shub login command specifies that the scrapy cloud API key is at https://app.zyte.com/account/apikey but it's actually zyte API key page. Scrapy cloud api keys are in https://app.zyte.com/o/settings/apikey.
This PR fixes this reference.

Fix API key setting page URL
